name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    name: generate snake gif
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: Mebin-7711
          outputs: |
            ./output/github-contribution-grid-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generate contribution snake"
          add: "output/github-contribution-grid-snake.svg"
